---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: elyra-aidevsecops-tutorial
spec:
  replicas: 1
  selector:
    service: elyra-aidevsecops-tutorial
    app.kubernetes.io/name: thoth
    app.kubernetes.io/component: aicoe-gather-metrics-pipeline
    app.kubernetes.io/managed-by: aicoe-thoth-devops
  template:
    metadata:
      labels:
        service: elyra-aidevsecops-tutorial
        app.kubernetes.io/name: thoth
        app.kubernetes.io/component: aicoe-gather-metrics-pipeline
        app.kubernetes.io/managed-by: aicoe-thoth-devops
    spec:
      containers:
        - name: elyra-aidevsecops-tutorial
          image: quay.io/thoth-station/elyra-aidevsecops-tutorial:v0.13.1
          env:
            - name: WEB_CONCURRENCY
              value: "1"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "384Mi"
              cpu: "100m"
            limits:
              memory: "768Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
  test: false
