---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: elyra-aidevsecops-tutorial
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: neural-magic-deepsparse
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: elyra-aidevsecops-pytorch-inference
spec:
  lookupPolicy:
    local: true
