---
kind: Service
apiVersion: v1
metadata:
  name: elyra-aidevsecops-tutorial
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    service: elyra-aidevsecops-tutorial
