check:
  - thoth-build
  - thoth-precommit
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.20.1
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: elyra-aidevsecops-tutorial
  registry-secret: thoth-station-thoth-pusher-secret
deploy:
  project-org: "thoth-station"
  project-name: "elyra-aidevsecops-tutorial"
  image-name: "elyra-aidevsecops-tutorial"
  overlay-contextpath: "manifests/overlays/test/imagestreamtag.yaml"
