presubmits:
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.12.7
          command:
            - "pre-commit"
            - "run"
            - "--all-files"
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"

  - name: thoth-mypy-py38
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/mypy
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-pytest-ubi8-py38:v0.12.5
          command:
            - "/usr/local/bin/mypy"
            - "."
            - "--ignore-missing-imports"
          resources:
            requests:
              memory: "2Gi"
              cpu: "200m"
