host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv
overlays_dir: overlays

runtime_environments:
  - name: experiment
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

  - name: download-dataset
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

  - name: training
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: performance

  - name: inference
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: security

  - name: test-model
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

  - name: nm-download
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

  - name: pytorch-training
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: performance

  - name: nm-convert-onnx
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

  - name: nm-sparseml
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: performance

  - name: nm-inference
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: performance

  - name: pytorch-inference
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: performance



managers:
  - name: thoth-advise
    configuration:
      labels: [bot]
  - name: info
  - name: version
    configuration:
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
      changelog_smart: true
