apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: <CHANGE_ME>
  name: <CHANGE_ME>
spec:
  schedule: "0 0 1 * *"
  concurrencyPolicy: "Replace"
  workflowSpec:
    volumeClaimTemplates:
      - metadata:
          name: local-data-storage
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    entrypoint: entrypoint
    templates:
    - name: entrypoint
      steps:
      - - name: execute-template
          templateRef:
            name: <CHANGE_ME>
            template: entrypoint
