kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: <CHANGE_ME>
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: <QUAY_IMAGE_URL>
