apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: neural-magic-deepsparse
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/thoth-station/neural-magic-deepsparse:v0.13.0
      importPolicy: {}
      referencePolicy:
        type: Source
